<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * AI-written insights about someone or something (spec 0005 §3.5, §4.1):
 * a learner's coaching summary, a hotel's dashboard briefing.
 *
 * One row per (subject, kind), rewritten when the data behind it changes
 * (`fingerprint`). Generated by a queued job, never in a request (PERF-04),
 * with the status the page polls. The payload is the AI's structured
 * output only; everything it links to is computed on the server.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('ai_insights', function (Blueprint $table): void {
            $table->id();
            $table->morphs('subject');
            $table->string('kind', 40);
            $table->foreignId('hotel_id')->nullable()->constrained()->nullOnDelete();
            $table->string('status', 20);
            $table->json('payload')->nullable();
            $table->string('fingerprint', 64)->nullable();
            $table->string('failed_reason', 500)->nullable();
            $table->timestamp('generated_at')->nullable();
            $table->timestamps();

            $table->unique(['subject_type', 'subject_id', 'kind']);
            $table->index(['hotel_id', 'kind']);
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('ai_insights');
    }
};
